baseurl = "http://hugo-hello-world-jm-demo-e6fe9f27.apps.thedigitalgarage.io"
languageCode = "en-us"
title = "mfojtik blog"
log = true
relativeURL = true

[params]
  Subtitle = "Look at you, hacker. A pathetic creature of meat and bone, panting and sweating as you run through my corridors. How can you challenge perfect immortal machine"
  Summary = true
  Content = true
